### ISSUE TITLE
Dont working in Firefox

### ISSUE THREAD

**Issue by JonhnyDev** [fingerprintjs/fingerprintjs-pro-react#24]
I installed on NextJS, the latest version, it works great for google Chmmo, Vivaldi, Brave and Opera, but on FireFox of the following error:

error.message FPJSAgentError: Error: Network connection error
And:
Requisição cross-origin bloqueada: A diretiva de mesma origem (same origin policy) impede a leitura do recurso remoto em https://api.fpjs.io/?ci=js/3.6.1 (motivo: falha na requisição CORS). Código de status: (null).

![image](https://user-images.githubusercontent.com/43152652/163501917-fa3fc160-7768-4d8e-a0ac-9a46b2b1fc8e.png)

**Comment by ilfa** [comment]
Hi @JonhnyDev, thanks for trying our integration!

The problem that you get is mostly about our FingerprintJS Pro Agent. It makes XHR requests to our servers for better device identification. And adblocking and tracking prevention mechanisms don't allow it for privacy reasons as Firefox does in your case. You can read more about it on the official [Firefox support page](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop). And you can turn it off for you the development environment if you just want to test something.

Identification still works with blocked requests, but with decreased accuracy. We have subdomain integration to fix this problem. To use it you need to make some configurations on your side. More info you can find in the [documentation](https://dev.fingerprintjs.com/docs/subdomain-integration).

To configure this integration you need to pass an additional option `endpoint` to `FpjsProvider` `loadOptions`as in the example below:

```jsx
<FpjsProvider
    loadOptions = {{
      apiKey: 'your-fpjs-public-api-key',
      endpoint: 'https://fp.yourdomain.com'
    }}
  >
    <App />
  </FpjsProvider>
```

But according using integration with NextJS, we have the problem with exceptions on the server-side, that we fixed in #23.

**Comment by JonhnyDev** [comment]
Dont working...
![image](https://user-images.githubusercontent.com/43152652/163604680-5814ae98-6ead-4bc2-b215-2d793044b8d2.png)
![image](https://user-images.githubusercontent.com/43152652/163604692-09bcde16-2280-43c3-aaa0-093e26db81f9.png)
![image](https://user-images.githubusercontent.com/43152652/163604708-d0408a6b-d27c-433a-9cac-e8b0d7fd77c5.png)
![image](https://user-images.githubusercontent.com/43152652/163604731-af6b0280-6f9e-45f5-8f34-491ab58c1b52.png)

even configured with the right DNS "A" and propagated, it continues to give error.
IP: 15.197.245.112

Erros:
error.message FPJSAgentError: Error: Network connection error
trycatch.js:220          POST https://fp.chatcomposer.com/?ci=js/3.6.1 net::ERR_NAME_NOT_RESOLVED

**Comment by JonhnyDev** [comment]
working, thank you

**Comment by Valve** [comment]
@JonhnyDev if the proposed solution has worked for you, please consider closing this issue. Thanks
